branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - backend-test
          - frontend-test
          - security-scan
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      enforce_admins: true
      restrictions: null

  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - backend-test
          - frontend-test
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      enforce_admins: false
      restrictions: null

  - name: 'feature/*'
    protection:
      required_status_checks:
        strict: true
        contexts:
          - backend-test
          - frontend-test
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: false
      restrictions: null 