# Database Configuration
database:
  host: localhost
  port: 5432
  name: script_game_db
  user: postgres
  password: ${DB_PASSWORD}
  max_connections: 100
  pool_size: 20

# Server Configuration
server:
  host: 0.0.0.0
  port: 8000
  debug: false
  secret_key: ${SERVER_SECRET_KEY}
  cors_origins:
    - http://localhost:3000
    - https://yourdomain.com

# API Configuration
api:
  version: v1
  base_url: /api/v1
  cors_origins: ["http://localhost:3000"]
  rate_limit: 100

# AI Model Settings
ai_models:
  model_path: ./models
  cache_dir: ./cache
  max_tokens: 2048
  temperature: 0.7
  timeout: 30

# Logging Configuration
logging:
  level: INFO
  file: ./logs/app.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_size: 100MB
  backup_count: 10

redis:
  host: localhost
  port: 6379
  db: 0

voice_service:
  host: 0.0.0.0
  port: 7777
  max_rooms: 100
  max_users_per_room: 10
  audio_quality:
    sample_rate: 48000
    channels: 2
    bitrate: 128000

ai_service:
  model_path: ./models
  max_tokens: 2048
  temperature: 0.7
  batch_size: 32
  cache_size: 1000

questionnaire:
  min_questions: 10
  max_questions: 30
  analysis_batch_size: 50

script_engine:
  max_players: 10
  min_players: 4
  default_difficulty: 3
  cache_timeout: 3600

security:
  jwt_secret: your-secret-key
  token_expire_minutes: 60
  password_min_length: 8
  max_login_attempts: 5

monitoring:
  enabled: true
  prometheus_port: 9090
  grafana_port: 3000
